
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package rover;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\020\000\002\002\004\000\002\002\003\000\002\003" +
    "\004\000\002\003\003\000\002\004\004\000\002\004\004" +
    "\000\002\004\004\000\002\005\006\000\002\006\006\000" +
    "\002\007\006\000\002\011\003\000\002\011\003\000\002" +
    "\012\003\000\002\012\003\000\002\010\003\000\002\010" +
    "\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\036\000\010\004\005\011\010\012\004\001\002\000" +
    "\004\013\034\001\002\000\006\005\027\006\031\001\002" +
    "\000\004\021\026\001\002\000\004\021\025\001\002\000" +
    "\006\007\020\010\022\001\002\000\004\002\017\001\002" +
    "\000\012\002\000\004\005\011\010\012\004\001\002\000" +
    "\004\021\015\001\002\000\012\002\ufffe\004\ufffe\011\ufffe" +
    "\012\ufffe\001\002\000\012\002\ufffc\004\ufffc\011\ufffc\012" +
    "\ufffc\001\002\000\012\002\uffff\004\uffff\011\uffff\012\uffff" +
    "\001\002\000\004\002\001\001\002\000\004\022\ufff5\001" +
    "\002\000\004\022\023\001\002\000\004\022\ufff4\001\002" +
    "\000\004\020\024\001\002\000\004\021\ufff9\001\002\000" +
    "\012\002\ufffb\004\ufffb\011\ufffb\012\ufffb\001\002\000\012" +
    "\002\ufffd\004\ufffd\011\ufffd\012\ufffd\001\002\000\004\022" +
    "\ufff7\001\002\000\004\022\032\001\002\000\004\022\ufff6" +
    "\001\002\000\004\017\033\001\002\000\004\021\ufffa\001" +
    "\002\000\004\014\035\001\002\000\006\015\040\016\036" +
    "\001\002\000\004\021\ufff2\001\002\000\004\021\ufff8\001" +
    "\002\000\004\021\ufff3\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\036\000\016\002\010\003\011\004\013\005\005\006" +
    "\012\007\006\001\001\000\002\001\001\000\004\011\027" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\012" +
    "\020\001\001\000\002\001\001\000\012\004\015\005\005" +
    "\006\012\007\006\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\010\036\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // Custom syntax error handling to report line and column of the illegal token
    public void syntax_error(Symbol cur_token) {
        String tokenName = "Desconocido";
        if (cur_token.sym < sym.terminalNames.length) {
            tokenName = sym.terminalNames[cur_token.sym];
        }
        String valueStr = (cur_token.value != null) ? cur_token.value.toString() : "";
        String msg = "Error sintáctico: Token inesperado '" + tokenName + "'" + 
                     (valueStr.isEmpty() ? "" : " (con valor: \"" + valueStr + "\")") +
                     " en línea " + cur_token.left + ", columna " + cur_token.right;
        throw new RuntimeException(msg);
    }

    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        // Prevent default error recovery messages
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Prog EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Result start_val = (Result)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Prog ::= ListaComandos 
            {
              Result RESULT =null;
		int lcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Result lc = (Result)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new Result(lc.simulation, new Node("Prog", lc.node));
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Prog",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // ListaComandos ::= ListaComandos Comando 
            {
              Result RESULT =null;
		int lcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lcright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Result lc = (Result)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Result c = (Result)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        String sim = lc.simulation + "\n" + c.simulation;
        RESULT = new Result(sim, new Node("ListaComandos", lc.node, c.node));
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListaComandos",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // ListaComandos ::= Comando 
            {
              Result RESULT =null;
		int cleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Result c = (Result)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        RESULT = new Result(c.simulation, new Node("ListaComandos", c.node));
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ListaComandos",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Comando ::= Movimiento PUNTO_COMA 
            {
              Result RESULT =null;
		int mleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int mright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Result m = (Result)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        RESULT = new Result(m.simulation, new Node("Comando", m.node, new Node(";")));
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Comando",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Comando ::= Giro PUNTO_COMA 
            {
              Result RESULT =null;
		int gleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int gright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Result g = (Result)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        RESULT = new Result(g.simulation, new Node("Comando", g.node, new Node(";")));
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Comando",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Comando ::= Recoleccion PUNTO_COMA 
            {
              Result RESULT =null;
		int rleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int rright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Result r = (Result)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        RESULT = new Result(r.simulation, new Node("Comando", r.node, new Node(";")));
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Comando",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Movimiento ::= MOVE DirMov NUMERO METERS 
            {
              Result RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Result d = (Result)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        String sim = "[Simulación] Moviendo " + d.simulation + " " + n + " metros.";
        Node node = new Node("Movimiento", 
                            new Node("MOVE"), 
                            d.node, 
                            new Node(String.valueOf(n)), 
                            new Node("METERS"));
        RESULT = new Result(sim, node);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Movimiento",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Giro ::= TURN DirGiro NUMERO DEGREES 
            {
              Result RESULT =null;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Result d = (Result)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer n = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
        String sim = "[Simulación] Girando a la " + d.simulation + " " + n + " grados.";
        Node node = new Node("Giro", 
                            new Node("TURN"), 
                            d.node, 
                            new Node(String.valueOf(n)), 
                            new Node("DEGREES"));
        RESULT = new Result(sim, node);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Giro",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Recoleccion ::= TAKE SAMPLE FROM Terreno 
            {
              Result RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Result t = (Result)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
        String sim = "[Simulación] Recolectando muestra de " + t.simulation + ".";
        Node node = new Node("Recoleccion", 
                            new Node("TAKE"), 
                            new Node("SAMPLE"), 
                            new Node("FROM"), 
                            t.node);
        RESULT = new Result(sim, node);
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Recoleccion",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // DirMov ::= FORWARD 
            {
              Result RESULT =null;
		
        RESULT = new Result("ADELANTE", new Node("DirMov", new Node("FORWARD")));
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DirMov",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // DirMov ::= BACKWARD 
            {
              Result RESULT =null;
		
        RESULT = new Result("ATRÁS", new Node("DirMov", new Node("BACKWARD")));
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DirMov",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // DirGiro ::= LEFT 
            {
              Result RESULT =null;
		
        RESULT = new Result("IZQUIERDA", new Node("DirGiro", new Node("LEFT")));
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DirGiro",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // DirGiro ::= RIGHT 
            {
              Result RESULT =null;
		
        RESULT = new Result("DERECHA", new Node("DirGiro", new Node("RIGHT")));
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("DirGiro",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // Terreno ::= SOIL 
            {
              Result RESULT =null;
		
        RESULT = new Result("SUELO", new Node("Terreno", new Node("SOIL")));
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Terreno",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // Terreno ::= ROCK 
            {
              Result RESULT =null;
		
        RESULT = new Result("ROCA", new Node("Terreno", new Node("ROCK")));
    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Terreno",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
