
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package rover;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TAKE = 8;
  public static final int FORWARD = 3;
  public static final int MOVE = 2;
  public static final int LEFT = 5;
  public static final int ROCK = 12;
  public static final int PUNTO_COMA = 15;
  public static final int BACKWARD = 4;
  public static final int EOF = 0;
  public static final int NUMERO = 16;
  public static final int RIGHT = 6;
  public static final int METERS = 13;
  public static final int TURN = 7;
  public static final int error = 1;
  public static final int FROM = 10;
  public static final int SAMPLE = 9;
  public static final int SOIL = 11;
  public static final int DEGREES = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MOVE",
  "FORWARD",
  "BACKWARD",
  "LEFT",
  "RIGHT",
  "TURN",
  "TAKE",
  "SAMPLE",
  "FROM",
  "SOIL",
  "ROCK",
  "METERS",
  "DEGREES",
  "PUNTO_COMA",
  "NUMERO"
  };
}

